services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Repository
    App\Repository\GameRepository:
        tags: ['app.repository']

    # Services
    App\Service\RandomNumberGenerator:
        tags: ['app.service']

    App\Service\PayoutCalculator:
        tags: ['app.service']

    App\Service\GameService:
        arguments:
            $gameRepository: '@App\Repository\GameRepository'
            $rng: '@App\Service\RandomNumberGenerator'
            $payoutCalculator: '@App\Service\PayoutCalculator'
        tags: ['app.service']

    # Controllers
    App\Controller\GameController:
        arguments:
            $gameService: '@App\Service\GameService'
        tags: ['controller.service_arguments']

    # Commands
    App\Command\GameSeederCommand:
        arguments:
            $gameService: '@App\Service\GameService'
        tags: ['console.command']

    App\Command\GameTestCommand:
        arguments:
            $gameService: '@App\Service\GameService'
        tags: ['console.command']

    App\Command\GameDemoCommand:
        arguments:
            $gameService: '@App\Service\GameService'
        tags: ['console.command']